import { BsNavigation } from "@/components/Navigation/BsNavigation";
import "./globals.css";
import { Inter } from "next/font/google";
import { Providers } from "../redux/provider";
import { store } from "../redux/store";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  manifest: "/manifest.json",
  viewport: "width=device-width, initial-scale=1",
  icons: ["/icon.png"],
  themeColor: "#ffffff",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="">
        <Providers>{children}</Providers>
        <BsNavigation />
      </body>
    </html>
  );
}
